language: csharp
dotnet: 2.0.0

before_install:
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - node --version

install:
  npm i -g typescript
  
script:
  - sudo cp /usr/lib/mono/4.5/System.Configuration.dll /usr/lib/mono/4.5/System.configuration.dll
  - export FrameworkPathOverride=/usr/lib/mono/4.5/
  - export EnableNuGetPackageRestore="true"
  - mono src/.nuget/NuGet.exe install Rosalia -ExcludeVersion -Prerelease
  - mono Rosalia/tools/Rosalia.exe /workDirectory=src /task=BuildPackages "CrystalQuartz.Build/CrystalQuartz.Build.csproj" 

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: Artifacts/gh_pages
  on:
    branch: quartz3

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fa02e86751dcd3aedd1f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always