language: csharp

before_install:
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - node --version

install:
  npm i -g typescript
  
script:
  - export EnableNuGetPackageRestore="true"
  - mono src/.nuget/NuGet.exe install Rosalia -ExcludeVersion -Prerelease
  - mono Rosalia/tools/Rosalia.exe /workDirectory=src "CrystalQuartz.Build/CrystalQuartz.Build.csproj" 

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fa02e86751dcd3aedd1f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
